import Cart from "@/components/cart";
import Product from "@/components/product";
import { ProductContext } from "@/context/ProductContext";
import Head from "next/head";
import { useContext } from "react";

export default function Home() {
  const context = useContext(ProductContext);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ display: "flex" }}>
        {context?.products?.map((product) => (
          <Product
            key={product.id}
            id={product.id}
            name={product.name}
            price={product.price}
            image={product.image}
          />
        ))}
        <Cart />
      </main>
    </>
  );
}
